USE master /* PASAMOS PRIMERO A MASTER PARA PODER BORRAR LA QUE ESTA EN USO */
GO
DROP DATABASE BLUEPRINT /* BORRAMOS BLUEPRINT  */
GO

CREATE DATABASE BLUEPRINT
GO

USE BLUEPRINT
/*GO
CREATE TABLE Localidades(
	CodigoPostal SMALLINT PRIMARY KEY IDENTITY(1, 1) NOT NUL,
	Ciudad VARCHAR(50) NOT  NULL,
	Provincia VARCHAR(50) NOT NULL
	Pais VARCHAR(50) NOT NULL
)*/
GO
CREATE TABLE Domicilios(
	Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Calle VARCHAR(50) NULL,
	Altura SMALLINT NULL,
	Ciudad VARCHAR(50) NULL,
	Pais VARCHAR(50) NULL
	)
GO
CREATE TABLE TiposCliente(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL
)
GO
CREATE TABLE Clientes(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	RazonSocial VARCHAR(100) NOT NULL,
	Cuit VARCHAR(11) NOT NULL UNIQUE,
	IidTipo INT NOT NULL FOREIGN KEY REFERENCES TiposCliente(Id),
	Email VARCHAR(50) NULL,
	Telefono VARCHAR(20) NULL,
	Celular VARCHAR(20) NULL, 
	IdDomicilio INT NULL FOREIGN KEY REFERENCES Domicilios(Id)
	
)
GO
CREATE TABLE Proyectos(
	Id VARCHAR(5) NOT NULL PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	Descripcion TEXT NULL,
	IdCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(Id),
	FechaInicio DATE NOT NULL,
	FechaFin DATE NULL,
	Costo MONEY NOT NULL,
	Estado BIT NOT NULL 
)
GO 
CREATE TABLE TiposModulos(
	Id SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(80) NOT  NULL, 
	Descripcion VARCHAR(80) NOT NULL 
)
GO
CREATE TABLE Modulos(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	IdTiposModulos SMALLINT NOT NULL FOREIGN KEY REFERENCES TiposModulos(Id),
	IdProyectos VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES Proyectos(Id),
	Costo DECIMAL NOT NULL, 
	FechaInicio SMALLDATETIME NOT NULL CHECK(FechaInicio > GETDATE()),
	FechaFin  SMALLDATETIME NOT NULL CHECK(FechaFin > GETDATE())
) 
GO
CREATE TABLE TiposColaboradores(
Id VARCHAR(1) NOT NULL PRIMARY KEY,
Descripcion VARCHAR(20) NOT NULL
)
GO
CREATE TABLE  Colaboradores(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Apellio VARCHAR(50) NOT NULL,
Nombre VARCHAR(40) NOT NULL,
Email VARCHAR(80) NULL, 
Celular VARCHAR(15) NULL,
IdDomicilio INT NULL FOREIGN KEY REFERENCES Domicilios(Id),
IdTiposColaboradores VARCHAR(1) FOREIGN KEY REFERENCES TIPOSCOLABORADORES(ID)
)
