USE master /* PASAMOS PRIMERO A MASTER PARA PODER BORRAR LA QUE ESTA EN USO */
GO
DROP DATABASE BluePrint /* BORRAMOS BluePrintNuevo  */
GO
CREATE DATABASE BluePrint
GO
USE BluePrint
GO
CREATE TABLE TiposDeClientes(
Id SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
Tipo VARCHAR(30) NOT NULL UNIQUE
)
GO
CREATE TABLE Clientes(
IdCliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Cuit VARCHAR(13) NOT NULL UNIQUE,
IdTipo SMALLINT NOT NULL FOREIGN KEY REFERENCES TiposDeClientes(Id),
RazonSocial VARCHAR(40) NOT NULL,
Mail VARCHAR(50) NULL,
Telefono VARCHAR(16) NULL,
Celular VARCHAR(16) NULL
)
GO
CREATE TABLE Proyectos(
Id VARCHAR(6) NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Descripcion VARCHAR(200) NULL,
IdCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IdCliente),
FechaInicio DATE NOT NULL,
FechaFin DATE NULL,
CostoEstimado MONEY NOT NULL CHECK(CostoEstimado<=0),
Estado BIT NOT NULL
)
GO
CREATE TABLE Paises(
Id SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(20) NOT NULL
)
GO
CREATE TABLE Ciudades(
Id SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
IdPais SMALLINT NOT NULL FOREIGN KEY REFERENCES Paises(Id),
Nombre VARCHAR(50) NOT NULL
)
GO
ALTER TABLE Clientes
ADD IdCiudad SMALLINT FOREIGN KEY REFERENCES Ciudades(Id) NULL
GO
CREATE TABLE Colaboradores(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Apellido VARCHAR(30) NOT NULL,
Nombre VARCHAR(30) NOT NULL,
Mail VARCHAR(50) NULL, 
Celular VARCHAR(15) NULL, 
CHECK (Celular IS NOT NULL or Mail IS NOT NULL),
FechaNacimiento DATE NOT NULL,
Domicilio VARCHAR(50) NULL,
CiudadId SMALLINT FOREIGN KEY REFERENCES Ciudades(Id) NULL,
Tipo CHAR NOT NULL CHECK(Tipo ='I' or Tipo ='E')
)
GO
CREATE TABLE Modulos(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IdProyecto VARCHAR(6) NOT NULL FOREIGN KEY REFERENCES Proyectos(Id),
Nombre VARCHAR(20) NOT NULL,
Descripcion VARCHAR(200) NULL,
TiempoHoras TINYINT NOT NULL,
CostoEstimado MONEY NOT NULL CHECK(CostoEstimado>0),
FechaInicio DATE NULL,
FechaEstimadaFin DATE NULL,
FechaFin DATE NULL
)
GO
CREATE TABLE TiposDeTareas(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	Nombre VARCHAR(50) NOT NULL
)
GO
CREATE TABLE Tareas(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
	IdModulo INT NOT NULL FOREIGN KEY REFERENCES Modulos(Id),
	IdTipos INT NOT NULL FOREIGN KEY REFERENCES TiposDeTareas(Id),
	IdProyectos VARCHAR(6) NOT NULL FOREIGN KEY REFERENCES Proyectos(Id),
	Costo MONEY NOT NULL CHECK(Costo >= 0),
	FechaInicio DATE NULL, 
	FechaFin DATE NULL,
	Estado BIT NOT NULL DEFAULT(1)
	)
GO
CREATE TABLE Colaboraciones(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	IdColaboradores INT NOT NULL FOREIGN KEY REFERENCES Colaboradores(Id),
	IdTiposDeTareas INT NOT NULL FOREIGN KEY REFERENCES TiposDeTareas(Id),
	IdModulo INT NOT NULL FOREIGN KEY REFERENCES Modulos(Id),
	Precio MONEY NOT NULL CHECK(Precio >=0),
	Tiempo SMALLINT NOT NULL CHECK(Tiempo >0),
	Estado BIT NOT NULL DEFAULT(1)
)
GO