CREATE DATABASE BLUEPRINT
GO

USE BLUEPRINT
GO

CREATE TABLE TiposCliente(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	nombre VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Clientes(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	razonSocial VARCHAR(100) NOT NULL,
	Cuit VARCHAR(11) NOT NULL UNIQUE,
	idTipo INT NOT NULL FOREIGN KEY REFERENCES TiposCliente(id),
	email VARCHAR(50) NULL,
	telefono VARCHAR(20) NULL,
	celular VARCHAR(20) NULL
)
GO

CREATE TABLE Proyectos(
	id VARCHAR(5) NOT NULL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	descripcion TEXT NULL,
	idCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(id),
	fechaInicio DATE NOT NULL,
	fechaFin DATE NULL,
	costo MONEY NOT NULL,
	estado BIT NOT NULL 
)